# Brightness
OVER_EXP_THRESHOLD = 255
UNDER_EXP_THRESHOLD = 120
OVER_EXP_WHITE_COUNT = 100

# Sharpness
VIEW_FINDER_SCALE_H = 0.52
VIEW_FINDER_SCALE_W = 0.15
SHARPNESS_THRESHOLD = 0.7

CROP_RATIO = 0.6

# Homography
MIN_MATCH_COUNT = 7

# Is centered
POSITION_THRESHOLD = 0.2

# Oritentation
ANGLE_THRESHOLD = 10
